import type { ContentFamily } from "../types.js";

/**
 * Play-by-play families. Every one of these must be selectable without an
 * `ApprovedPublicAnalysis` input — PBP is deterministic-first per the brief:
 * "the director must produce deterministic PBP or silence, rather than
 * inventing strategic explanation" when analysis is unavailable.
 *
 * Coverage note: this is the vertical slice, not the full taxonomy. Every
 * family here maps to an event `@pegboard/engine` can actually produce today.
 * Families that depend on concepts the engine doesn't model yet (skunk rules,
 * ranked stakes, replay, accessibility variants, cut-for-deal ceremony,
 * complex counted-pattern narration) are intentionally left for later —
 * see the delivery report for the full remaining list.
 */
export const PBP_FAMILIES: readonly ContentFamily[] = [
  {
    familyId: "PBP-06",
    role: "play_by_play",
    grade: "A",
    phases: ["starter_reveal"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 1,
    cooldownGroup: "starter_reveal",
    requiredPublicFacts: ["starter_card"],
    allowedPlaceholders: ["card"],
    forbiddenInferences: ["unrevealed_hand", "unrevealed_crib"],
    variants: [
      { tier: "clean", text: "Starter is the [card]." },
      { tier: "broadcast", text: "Starter is the [card]. Now we are live." },
      { tier: "arcade", text: "Starter's up: [card]!" },
      { tier: "learn", text: "The starter card is [card] — that card counts toward everyone's hand." },
    ],
  },
  {
    familyId: "PBP-07",
    role: "play_by_play",
    grade: "S",
    phases: ["starter_reveal"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 3,
    cooldownGroup: "his_heels",
    requiredPublicFacts: ["starter_card", "dealer"],
    allowedPlaceholders: ["dealer", "points"],
    forbiddenInferences: ["unrevealed_hand", "unrevealed_crib"],
    variants: [
      { tier: "clean", text: "Jack on the cut. His heels for [points]." },
      { tier: "broadcast", text: "Jack on the cut — his heels, [points] straight to [dealer]." },
      { tier: "arcade", text: "Jack on the cut — his heels for [points]!" },
      { tier: "learn", text: "His heels — that's [points] points automatically for [dealer], because the starter is a jack." },
      { tier: "kids", text: "A jack! [dealer] gets [points] free points right away." },
    ],
  },
  {
    familyId: "PBP-09",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["broadcast", "arcade", "learn", "expert"],
    intensityLevel: 1,
    cooldownGroup: "card_call",
    requiredPublicFacts: ["running_count"],
    allowedPlaceholders: ["count"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Count climbs to [count]." },
      { tier: "arcade", text: "Count's up to [count] — window's getting tight." },
      { tier: "learn", text: "The running count is now [count]." },
    ],
  },
  {
    familyId: "PBP-10",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "scoring_call",
    requiredPublicFacts: ["running_count", "points", "actor"],
    allowedPlaceholders: ["player", "afterScore", "points", "length"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Fifteen for [points]." },
      { tier: "broadcast", text: "Fifteen for [points]. [player] to [afterScore]." },
      { tier: "arcade", text: "Fifteen for [points]!" },
      { tier: "learn", text: "That makes fifteen — [player] scores [points] points." },
      { tier: "kids", text: "Fifteen! [points] points for [player]." },
    ],
  },
  {
    // `points` is parameterized for the same reason as PBP-13: a fifteen or
    // thirty-one can coincide with a pair on the same card, scoring more
    // than the "typical" two.
    familyId: "PBP-11",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "scoring_call",
    requiredPublicFacts: ["running_count", "points", "actor"],
    allowedPlaceholders: ["player", "afterScore", "points", "length"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Thirty-one exactly. [points] for [player]." },
      { tier: "broadcast", text: "Thirty-one on the nose. [player] moves to [afterScore]." },
      { tier: "arcade", text: "Thirty-one, right on the number!" },
      { tier: "learn", text: "That brings the count to exactly thirty-one — [player] scores [points]." },
    ],
  },
  {
    familyId: "PBP-12",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "scoring_call",
    requiredPublicFacts: ["points", "actor"],
    allowedPlaceholders: ["player", "points", "afterScore", "length"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Pair for [points]." },
      { tier: "broadcast", text: "Pair for [points], [player]." },
      { tier: "arcade", text: "Pair! [points] points." },
      { tier: "learn", text: "Two matching cards in a row — that's a pair, worth [points]." },
    ],
  },
  {
    // Points are parameterized rather than hardcoded "six": a pair royal can
    // land on the same card as a fifteen (e.g. the third of three 5s), which
    // scores 8 total, not 6 — the wording must reflect whatever actually
    // scored, not the family's typical value.
    familyId: "PBP-13",
    role: "play_by_play",
    grade: "S",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 3,
    cooldownGroup: "rare_pegging",
    requiredPublicFacts: ["points", "actor"],
    allowedPlaceholders: ["player", "points", "afterScore", "length"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Pair royal for [points]." },
      { tier: "broadcast", text: "Pair royal — [points] points for [player]." },
      { tier: "arcade", text: "Pair royal! [points] points in a hurry." },
      { tier: "learn", text: "Three matching cards in a row — that's a pair royal, worth [points]." },
    ],
  },
  {
    familyId: "PBP-14",
    role: "play_by_play",
    grade: "S",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "rare_pegging",
    requiredPublicFacts: ["points", "actor"],
    allowedPlaceholders: ["player", "points", "afterScore", "length"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "Four of a kind. [points] points." },
      { tier: "broadcast", text: "Double pair royal — [points] points for [player]." },
      { tier: "arcade", text: "Four of a kind! [points] points just detonated on the board." },
      { tier: "learn", text: "All four matching cards in a row — a double pair royal, worth [points]." },
    ],
  },
  {
    familyId: "PBP-15",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "scoring_call",
    requiredPublicFacts: ["points", "actor", "run_length"],
    allowedPlaceholders: ["player", "length", "points", "afterScore"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "That closes a run of [length] for [points]." },
      { tier: "broadcast", text: "Run of [length] — [points] for [player]." },
      { tier: "arcade", text: "Run of [length]! [points] points." },
      { tier: "learn", text: "Those cards land in sequence — a run of [length], worth [points]." },
    ],
  },
  {
    familyId: "PBP-16",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 1,
    cooldownGroup: "go_call",
    requiredPublicFacts: ["actor", "running_count"],
    allowedPlaceholders: ["player", "count"],
    forbiddenInferences: ["opponent_hand", "why_no_legal_card"],
    variants: [
      { tier: "clean", text: "Go at [count]." },
      { tier: "broadcast", text: "[player] has no answer — go at [count]." },
      { tier: "arcade", text: "Go! Nothing there for [player]." },
      { tier: "learn", text: "[player] can't play without going over 31, so that's a go." },
    ],
  },
  {
    familyId: "PBP-17",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 1,
    cooldownGroup: "go_call",
    requiredPublicFacts: ["actor", "points"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: ["opponent_hand"],
    variants: [
      { tier: "clean", text: "Last card for one." },
      { tier: "broadcast", text: "Last card played — one for [player]." },
      { tier: "arcade", text: "Last card! One more for [player]." },
      { tier: "learn", text: "[player] played the last card of the sequence, worth one point." },
    ],
  },
  {
    familyId: "PBP-20",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 3,
    cooldownGroup: "board_race",
    requiredPublicFacts: ["new_leader", "margin"],
    allowedPlaceholders: ["player", "margin"],
    forbiddenInferences: ["opponent_hand"],
    variants: [
      { tier: "clean", text: "[player] moves in front by [margin]." },
      { tier: "broadcast", text: "[player] takes the lead, up by [margin]." },
      { tier: "arcade", text: "[player] moves in front by [margin]!" },
      { tier: "learn", text: "[player] now has more points and leads by [margin]." },
    ],
  },
  {
    familyId: "PBP-21",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "board_race",
    requiredPublicFacts: ["tied_score"],
    allowedPlaceholders: [],
    forbiddenInferences: ["opponent_hand"],
    variants: [
      { tier: "clean", text: "Dead even on the board." },
      { tier: "arcade", text: "Tied up! Dead even." },
      { tier: "learn", text: "Both players have the same score now." },
    ],
  },
  {
    familyId: "PBP-22",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["broadcast", "arcade", "expert"],
    intensityLevel: 2,
    cooldownGroup: "board_race",
    requiredPublicFacts: ["margin"],
    allowedPlaceholders: ["margin"],
    forbiddenInferences: ["opponent_hand"],
    variants: [
      { tier: "clean", text: "That trims it to [margin]." },
      { tier: "arcade", text: "That cuts the gap to [margin]!" },
    ],
  },
  {
    familyId: "PBP-24",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "finish_line",
    requiredPublicFacts: ["distance_to_win"],
    allowedPlaceholders: ["player", "distance"],
    forbiddenInferences: ["opponent_hand", "future_card"],
    variants: [
      { tier: "clean", text: "[player] is within [distance] of the line." },
      { tier: "broadcast", text: "[player] is closing in — [distance] from the win." },
      { tier: "arcade", text: "[player] is [distance] away from slamming the door!" },
      { tier: "learn", text: "[player] needs just [distance] more points to win." },
    ],
  },
  {
    familyId: "PBP-26",
    role: "play_by_play",
    grade: "A",
    phases: ["counting"],
    modeAllowlist: ["broadcast", "arcade", "learn", "expert"],
    intensityLevel: 1,
    cooldownGroup: "count_open",
    requiredPublicFacts: ["actor"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: ["unrevealed_hand"],
    variants: [
      { tier: "clean", text: "Now we count [player]'s hand." },
      { tier: "arcade", text: "Count time — let's see what [player] is holding." },
      { tier: "learn", text: "Time to count [player]'s hand and add up the points." },
    ],
  },
  {
    familyId: "PBP-32",
    role: "play_by_play",
    grade: "A",
    phases: ["counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids"],
    intensityLevel: 2,
    cooldownGroup: "hand_total",
    requiredPublicFacts: ["actor", "points"],
    allowedPlaceholders: ["player", "total"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "[player] finishes with [total]." },
      { tier: "broadcast", text: "[player]'s hand counts [total]." },
      { tier: "arcade", text: "[player] finishes with [total]!" },
      { tier: "learn", text: "[player]'s hand adds up to [total] points." },
    ],
  },
  {
    familyId: "PBP-33",
    role: "play_by_play",
    grade: "S",
    phases: ["counting"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 3,
    cooldownGroup: "big_hand",
    requiredPublicFacts: ["actor", "points"],
    allowedPlaceholders: ["player", "total"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "[total] points — that's a big hand." },
      { tier: "broadcast", text: "[total] points for [player] — that's a monster hand." },
      { tier: "arcade", text: "[total]! That is a monster hand." },
      { tier: "learn", text: "[player] found [total] points in that hand — well above average." },
    ],
  },
  {
    familyId: "PBP-34",
    role: "play_by_play",
    grade: "A",
    phases: ["crib"],
    modeAllowlist: ["broadcast", "arcade", "learn", "expert"],
    intensityLevel: 1,
    cooldownGroup: "count_open",
    requiredPublicFacts: ["actor"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: ["unrevealed_crib"],
    variants: [
      { tier: "clean", text: "Now the crib for [player]." },
      { tier: "arcade", text: "Crib time for [player]." },
      { tier: "learn", text: "Now we count the crib, which belongs to [player] this hand." },
    ],
  },
  {
    familyId: "PBP-36",
    role: "play_by_play",
    grade: "S",
    phases: ["crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 3,
    cooldownGroup: "big_hand",
    requiredPublicFacts: ["actor", "points", "afterScore"],
    allowedPlaceholders: ["player", "total", "afterScore"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "[total] in the crib. [player] storms into it." },
      { tier: "broadcast", text: "[total] in the crib for [player] — that's a real swing, up to [afterScore]." },
      { tier: "arcade", text: "[total] in the crib! The board just flipped." },
      { tier: "learn", text: "The crib came through big — [total] points, moving [player] to [afterScore]." },
    ],
  },
  {
    familyId: "PBP-38",
    role: "play_by_play",
    grade: "S",
    phases: ["counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "rare_hand",
    requiredPublicFacts: ["points"],
    allowedPlaceholders: ["total", "player"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "You don't see [total] very often." },
      { tier: "broadcast", text: "[total] points — that is a rare hand." },
      { tier: "arcade", text: "You do NOT see [total] very often!" },
      { tier: "learn", text: "A hand worth [total] points is unusual — most hands score much less." },
    ],
  },
  {
    familyId: "PBP-39",
    role: "play_by_play",
    grade: "S",
    phases: ["counting"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "rare_hand",
    requiredPublicFacts: ["actor", "points"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "Twenty-nine. The perfect hand." },
      { tier: "broadcast", text: "Twenty-nine for [player] — the perfect hand." },
      { tier: "arcade", text: "TWENTY-NINE. The perfect hand!" },
      { tier: "learn", text: "That's a twenty-nine — the highest possible cribbage hand." },
    ],
  },
  {
    familyId: "PBP-40",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "match_end",
    requiredPublicFacts: ["actor", "afterScore"],
    allowedPlaceholders: ["player", "points"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "[player] pegs out and wins it." },
      { tier: "broadcast", text: "[player] pegs out — that's the game." },
      { tier: "arcade", text: "[player] pegs out and wins it. Ballgame!" },
      { tier: "learn", text: "[player] reached the target score and wins the game." },
      { tier: "kids", text: "[player] wins! Great game!" },
    ],
  },
  {
    // ARC-03: player scores the exact points needed to win (no overshoot) — a
    // sharper, more emphatic call than PBP-40's generic exact-out. The
    // director prefers this over PBP-40 only when the win lands exactly on
    // the target score.
    familyId: "ARC-03",
    role: "play_by_play",
    grade: "S",
    phases: ["pegging", "counting", "crib"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "match_end",
    requiredPublicFacts: ["actor", "points", "target_score"],
    allowedPlaceholders: ["player", "points"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "[points] is all [player] needed. Walk it off." },
      { tier: "broadcast", text: "[player] finds exactly [points] to win it." },
      { tier: "arcade", text: "[points] is all [player] needed. WALK IT OFF!" },
      { tier: "learn", text: "[player] scored exactly the [points] points needed to reach the target and win." },
    ],
  },
  {
    // ARC-04: a non-scoring play immediately forces the opponent into a go —
    // upgrades what would otherwise be a routine, silenced play into a real
    // call. Detected via `revealedFacts` containing "followed_by_go", set by
    // the engine adapter from the same event batch (both facts are public:
    // the card played and the opponent's inability to answer it).
    familyId: "ARC-04",
    role: "play_by_play",
    grade: "A",
    phases: ["pegging"],
    modeAllowlist: ["broadcast", "arcade", "expert"],
    intensityLevel: 2,
    cooldownGroup: "count_control_call",
    requiredPublicFacts: ["actor", "followed_by_go"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: ["opponent_hand", "prevented_card"],
    variants: [
      { tier: "clean", text: "[player] slams the door on that count." },
      { tier: "broadcast", text: "[player] closes it off — no answer for the other side." },
      { tier: "arcade", text: "[player] slams the door on that count!" },
      { tier: "expert", text: "[player] took the count to a total that left no legal reply." },
    ],
  },
  {
    familyId: "PBP-41",
    role: "play_by_play",
    grade: "S",
    phases: ["pegging"],
    modeAllowlist: ["minimal", "broadcast", "arcade", "learn", "expert", "kids", "quiet"],
    intensityLevel: 4,
    cooldownGroup: "match_end",
    requiredPublicFacts: ["actor"],
    allowedPlaceholders: ["player"],
    forbiddenInferences: [],
    variants: [
      { tier: "clean", text: "That ends it right there — no more counting needed." },
      { tier: "broadcast", text: "[player] walks it off — no counting needed, that's the win." },
      { tier: "arcade", text: "Walk it off! [player] ends it before the count even happens." },
      { tier: "learn", text: "[player] reached the target during pegging, so the hand ends immediately — the rest doesn't get counted." },
    ],
  },
];
